# Generated by Django 5.0.6 on 2024-05-27 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 10, 20, 39, 561524)),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='static/upload/profile_images/'),
        ),
    ]
