# Generated by Django 5.0.6 on 2024-05-27 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_article_date_alter_author_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 11, 24, 23, 595090)),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/upload/article_images/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(upload_to='static/upload/profile_images/'),
        ),
    ]
