# Generated by Django 5.0.6 on 2024-05-28 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_alter_tag_options_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 16, 30, 22, 872319)),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='static/upload/article_images/default.jpg', upload_to='static/upload/article_images/'),
        ),
    ]
